// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nsmtaywqzutcdarchqjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5zbXRheXdxenV0Y2RhcmNocWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjg3NjIsImV4cCI6MjA2MzgwNDc2Mn0.VASNBC71FSSpLPWoxoTuEwlIGHdCt5XLDNM_tFlU8Ys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);